=== blockchain-lexicon-en-fr/blockchain-lexicon-en-fr/blockchainLexicon.xsd
<?xml version="1.0" encoding="UTF-8"?> <!--Adrien Dubied 2021 -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"> <!--Declaration of the root element of the XML Schema -->
    <xs:import namespace="http://www.w3.org/XML/1998/namespace" 
        schemaLocation="https://www.w3.org/2009/01/xml.xsd" /> <!-- Additional import from w3.org in order to declare the xml:lang attribute. -->
        <xs:element name="tmx">     <!--Declaration of the root element of the XML document -->
            <xs:complexType>        <!--The tmx element is a complexe type because it contains child elements and attributes. -->
    <xs:sequence>
        <xs:element ref="header"/> <!-- Child elements that are contained within the tmx element and their order -->
        <xs:element ref="body"/>   
     </xs:sequence>
                <xs:attribute name="version" use="required" type="xs:integer"/> <!-- Attribute that is contained within the tmx element. The use is mandatory and the data type is integer.-->
    </xs:complexType>
</xs:element>
        <xs:element name="header"> <!--The header element is a complexe type because it contains attributes. -->
        <xs:complexType>
            <xs:attribute name="creationTool" use="required" type="xs:string"/> <!-- List of attributes that are contained within the header element. Their use is mandatory and the data type is string.-->
            <xs:attribute name="creationToolVersion" use="required" type="xs:string"/>
            <xs:attribute name="segType" use="required" type="xs:string"/>
            <xs:attribute name="adminLang" use="required" type="xs:string"/>
            <xs:attribute name="srcLang" use="required" type="xs:string"/>
            <xs:attribute name="dataType" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
        <xs:element name="body"> <!--The body element is a complexe type because it contains a child element. -->
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="tu" maxOccurs="unbounded"/> <!--The child element's occurence is set unbounded because this will allow to create more tu elements in the future, when the term base will have to be increased with new terms. -->
            </xs:sequence>
        </xs:complexType>
    </xs:element>
        <xs:element name="tu"> <!--The tu element is a complexe type because it contains a child element. -->
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="tuv" maxOccurs="unbounded"/> <!--The child element's occurence is set unbounded because this will allow to create more tu elements in the future, when the term base will have to be increased with new languages.. -->
            </xs:sequence>
        </xs:complexType>
    </xs:element>
        <xs:element name="tuv"> <!--The tuv element is a complexe type because it contains a child elements and attributes. -->
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="term"/> <!--Declaration of the child element.-->
                <xs:element ref="definition"/> <!--Declaration of the child element.-->   
            </xs:sequence>
            <xs:attribute ref="xml:lang" use="required"/> <!--Declaration of the attribute which is mandatory in order tp manage the xml document according to language combinations.-->
        </xs:complexType>
    </xs:element>
        <xs:element name="term" type="xs:string"/> <!--Declaration of a simple type element. It only contains strings-->
        <xs:element name="definition" type="xs:string"/> <!--Declaration of a simple type element. It only contains strings-->
</xs:schema>

=== blockchain-lexicon-en-fr/blockchain-lexicon-en-fr/blockchainLexiconEnFr.xml
<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/css" href="lexicon.css"?>
<!-- DTD Schema:
First, the DTD schema gets declared with the indication of the root element of the file(line 16)
We declare the root element of our xml document and the child elements it contains (line 17)
We indicate the attribut that is contained in the root element and it's use: #REQUIRED (line 18)
We declare the "heder" element and indicate that this element will not contain any children nore data (line 19)
We indicate the attributes that are contained in the "header element", the data they have to contain and their use: #REQUIRED (Lines 20-25)
We declare the "body element" and the chil elements that he contains. With the + we indicate that the child element can occur at least once or more. (line 26)
We declare the "tu" element and indicate the child elements it contains. With the + we indicate that the child element can occur at least once or more. (line 27)
We declare the "tuv" element and indicate the corresponding child elements. With the absence of sings next to the child elements (*, +, ?), we mean that the child elements can occur once and only once. (line 28)
We declare the "term" element and indicate the type of data it can contain: text. (line 29)
We declare the "definition" element and indicate the type of data it can contain: text. (line 30)
We indicate the attributes that are contained in the "tuv" element, the data it has to contain and it's use: #REQUIRED (Line 31)
-->
<!--Adrien Dubied 2021 -->
<!DOCTYPE tmx [                                    
<!ELEMENT tmx (header, body)>
<!ATTLIST tmx version CDATA #REQUIRED>
<!ELEMENT header EMPTY>
<!ATTLIST header creationTool CDATA #REQUIRED>
<!ATTLIST header creationToolVersion CDATA #REQUIRED>
<!ATTLIST header segType CDATA #REQUIRED>
<!ATTLIST header adminLang CDATA #REQUIRED>
<!ATTLIST header srcLang CDATA #REQUIRED>
<!ATTLIST header dataType CDATA #REQUIRED>
<!ELEMENT body (tu+)>
<!ELEMENT tu (tuv+)>
<!ELEMENT tuv (term, definition)>
<!ELEMENT term (#PCDATA)>
<!ELEMENT definition (#PCDATA)>
<!ATTLIST tuv xml:lang CDATA #IMPLIED>
]>



<tmx version="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="blockchainLexicon.xsd">
   <header creationTool="Translate - Toolkit po2tmx" creationToolVersion="1.9.0" segType="term"
        adminLang="en" srcLang="en" dataType="plainText"/>
   <body>
       <tu>
           <tuv xml:lang="en">
               <term>Blockchain</term>
               <definition>Decentralised, encrypted and self-executing technology enabling the recording of lists of transactions. Transactions are only accepted if all the users agree that it is legitimate. Its best-known use is for digital currencies such as Bitcoin. By embedding code in the blockchain, transactions can be executed automatically in response to certain conditions being met, providing a 'guarantee of execution’. Self-executing smart contracts based upon this functionality are developing rapidly.</definition>
           </tuv>
           <tuv xml:lang="fr">
               <term>Chaîne de bloc</term>
               <definition>Technologie décentralisée, cryptée et auto-exécutoire permettant de tenir un registre de transactions de manière transparente et décentralisée. Une transaction n’est acceptée que si l’ensemble des utilisateurs s’accordent sur sa légitimité. Elle est surtout connue pour être à la base de devises numériques comme le bitcoin. En incorporant du code informatique à la chaîne de blocs, des transactions peuvent être exécutées automatiquement lorsque certaines conditions sont remplies, ce qui offre une « garantie d’exécution ». Ces contrats intelligents qui s’exécutent automatiquement en tirant parti de cette fonctionnalité connaissent un développement rapide.</definition>
           </tuv>
       </tu>
       
       <tu>
           <tuv xml:lang="en">
               <term>Decentralisation</term>
               <definition>In working progress…</definition>
           </tuv>
           <tuv xml:lang="fr">
               <term>Décentralisation</term>
               <definition>En cours d’élaboration…</definition>
           </tuv>
       </tu>

       <tu>
           <tuv xml:lang="en">
               <term>Ledger</term>
               <definition>In working progress…</definition>
           </tuv>
           <tuv xml:lang="fr">
               <term>Registre</term>
               <definition>En cours d’élaboration…</definition>
           </tuv>
       </tu>

       <tu>
           <tuv xml:lang="en">
               <term>Middleman</term>
               <definition>Intermediary which is trusted by all users, who has total control over the system and is responsible for mediating every transaction on a ledger (for example banks, governments, etc.).</definition>
           </tuv>
           <tuv xml:lang="fr">
               <term>Intermédiaire </term>
               <definition>Partie qui a la confiance de tous les utilisateurs, qui a le contrôle total du système et qui est responsable de la médiation de chaque transaction figurant dans le registre (banques, gouvernements, etc.).</definition>
           </tuv>
       </tu>

       <tu>
           <tuv xml:lang="en">
               <term>Hashing</term>
               <definition>Feature of the blockchain technology. It is a process through which a document is transformed into a fixed length code which is described as a digital fingerprint.</definition>
           </tuv>
           <tuv xml:lang="fr">
               <term>Hachage</term>
               <definition>Caractéristique de la technologie blockchain. Il s'agit d'un processus par lequel un document est transformé en un code de longueur fixe qui est décrit comme une empreinte numérique.</definition>
           </tuv>
       </tu>

       <tu>
           <tuv xml:lang="en">
               <term>Pseudonymity</term>
               <definition>Feature of the blockchain technology. The fact that all transactions are transparent, but they are not explicitly connected to real-world individuals or organisations, shielding the identity of parties along the supply chain without compromising the integrity of the record.</definition>
           </tuv>
           <tuv xml:lang="fr">
               <term>Pseudonymat </term>
               <definition>Caractéristique de la technologie blockchain. Le fait que toutes les transactions soient transparentes, mais qu'elles ne sont pas explicitement liées à des personnes ou à des organisations du monde réel, ce qui permet de protéger l'identité des parties tout au long de la chaîne d'approvisionnement sans compromettre l'intégrité de l'enregistrement.</definition>
           </tuv>
       </tu>

       <tu>
           <tuv xml:lang="en">
               <term>Nakamoto, Satoshi</term>
               <definition>It is the pseudonym for the mysterious and elusive publisher(s) of an article describing how cryptography, combined with a distributed public ledger, could be used to implement a digital currency without a central authority to authenticate payments. His article is the fundamental on which Satoshi Nakamoto launched the Bitcoin.</definition>
           </tuv>
           <tuv xml:lang="fr">
               <term>Nakamoto, Satoshi</term>
               <definition>Il s'agit du pseudonyme du ou des mystérieux et insaisissables éditeurs d'un article décrivant comment la cryptographie, combinée à un registre public distribué, pourrait être utilisée pour mettre en œuvre une monnaie numérique sans autorité centrale pour authentifier les paiements. Son article sert de fondement au développement du Bitcoin.</definition>
           </tuv>
       </tu>

       <tu>
           <tuv xml:lang="en">
               <term>Peer-to-peer</term>
               <definition>In working progress…</definition>
           </tuv>
           <tuv xml:lang="fr">
               <term>Pair à pair</term>
               <definition>En cours d’élaboration…</definition>
           </tuv>
       </tu>

       <tu>
           <tuv xml:lang="en">
               <term>Encrypt</term>
               <definition>In working progress…</definition>
           </tuv>
           <tuv xml:lang="fr">
               <term>Chiffrer</term>
               <definition>En cours d’élaboration…</definition>
           </tuv>
       </tu>

       <tu>
           <tuv xml:lang="en">
               <term>Watchdog</term>
               <definition>In working progress…</definition>
           </tuv>
           <tuv xml:lang="fr">
               <term>Organisme de surveillance</term>
               <definition>En cours d’élaboration…</definition>
           </tuv>
       </tu>

       <tu>
           <tuv xml:lang="en">
               <term>End-to-end encryption</term>
               <definition>In working progress…</definition>
           </tuv>
           <tuv xml:lang="fr">
               <term>Chiffrement de bout en bout </term>
               <definition>En cours d’élaboration…</definition>
           </tuv>
       </tu>

       <tu>
           <tuv xml:lang="en">
               <term>Mining</term>
               <definition>Process in which the transaction is packaged into a 'block' of transactions, and added, to the ever-growing list of blocks that form the blockchain ledger.</definition>
           </tuv>
           <tuv xml:lang="fr">
               <term>Minage</term>
               <definition>Processus au cours duquel les transactions sont regroupées en un "bloc" ajouté à la liste toujours croissante des blocs qui forment le registre de la blockchain.</definition>
           </tuv>
       </tu>

       <tu>
           <tuv xml:lang="en">
               <term>Scarcity</term>
               <definition>In working progress…</definition>
           </tuv>
